<?php 
/*
Plugin Name: Notitia FrontEnd Dashboard
Plugin URI: https://notitia.site
Description: Notitia Ai Platform Dashboard
Version: 
Author: Edze Worla Alex
Author URI: https://notitia.site
Text Domain: nfd
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}